routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
define("ADMIN", "admin/");
define("ADMIN_NAME", "admin.");
// define('USER_IMAGE','public/uploads/profile/avatar.png');
// define("ADMIN", "admin/");
define('INSERT_IMAGES','public/uploads/icons/insert-images.png');
// Admin Routes Start
// FRONTEND ROUTE


Route::get('/',['uses'=>'FrontController@index', 'as'=>'index']);
Route::get('/services',['uses'=>'FrontController@services', 'as'=>'services']);
Route::post('/contact_message',['uses'=>'FrontController@contact_message', 'as'=>'contact_message']);
// FORNTEND ROUTE END

// Auth::routes();

// LOGIN ROUTE START
Route::get(ADMIN.'login', ['uses'=>'Auth\LoginController@showLoginForm','as'=>'login']);
Route::post(ADMIN.'login', ['uses'=>'Auth\LoginController@login']);
Route::get(ADMIN.'logout',['uses'=>'Auth\LoginController@logout', 'as'=> 'logout']);
// LOGIN ROUTE END

// Route::post('logout', 'Auth\LoginController@logout')->name('logout');
// Route::get(ADMIN.'home', 'HomeController@index')->name('home');
Route::get(ADMIN.'/', ['uses'=>'HomeController@index', 'as'=>'home']);
Route::get(ADMIN.'/lock', ['uses' => 'ProfileController@lock', 'as' => 'lock']);
Route::post(ADMIN.'/lock', ['uses' => 'ProfileController@unLock', 'as' => 'lock']);
// Module routes start
Route::group(['prefix' =>ADMIN.'module', 'middleware' => ['auth','lock'], 'as' => 'module.'], function () {
	Route::get('/add',['uses' => 'ModuleController@create', 'as' => 'create'])->middleware('can:add-module');
	Route::post('/add',['uses' => 'ModuleController@store'])->middleware('can:add-module');
	Route::get('/list',['uses' => 'ModuleController@listModule','as' => 'list' ])->middleware('can:list-module');
	Route::get('/edit/{key}',['uses' => 'ModuleController@editModuleForm','as' => 'edit' ])->middleware('can:edit-module');
	Route::post('/edit/{key}',['uses' => 'ModuleController@updateModule'])->middleware('can:edit-module');
	Route::post('/delete',['uses' => 'ModuleController@deleteModule','as' => 'delete' ])->middleware('can:delete-module');
});
// Module route end

// Menu route start
Route::group(['prefix' =>ADMIN.'menu', 'middleware' => ['auth','lock'], 'as' => 'menu.'], function () {
	Route::get('/view/{id}',['uses' => 'ModuleController@viewMenu', 'as' => 'view']);
	Route::get('/add/{id}/{name}',['uses' => 'ModuleController@createMenu', 'as' => 'create']);
	Route::post('/store',['uses' => 'ModuleController@storeMenu','as' => 'store']);
});
// Menu route end

// users route start
Route::group(['prefix' =>ADMIN.'user', 'middleware' => ['auth','lock'], 'as' => 'user.'], function () {
	Route::get('/register',['uses'=>'UserController@showRegistrationForm', 'as'=> 'register'])->middleware('can:add-user');
	Route::post('/register',['uses'=>'UserController@store'])->middleware('can:add-user');
	Route::get('/list',['uses'=>'UserController@listUser', 'as' => 'list'])->middleware('can:list-user');
	Route::get('/edit/{key}',['uses'=>'UserController@getEdit', 'as' => 'edit'])->middleware('can:edit-user');
	Route::post('/update/{key}',['uses'=>'UserController@update', 'as'=>'update'])->middleware('can:edit-user');
	Route::post('/delete',['uses'=>'UserController@delete', 'as'=>'delete'])->middleware('can:delete-user');
	Route::post('/suspend',['uses'=>'UserController@suspend', 'as'=>'suspend'])->middleware('can:suspend-user');
	Route::post('/restore',['uses'=>'UserController@restore', 'as'=>'restore'])->middleware('can:suspend-user');
});
// users route end

// roles route start
Route::group(['prefix' =>ADMIN.'role', 'middleware' => ['auth','lock'], 'as' => 'role.'], function () {
	Route::any('/list', ['uses' => 'RolesController@index', 'as' => 'list'])->middleware('can:list-role');
	Route::any('/add', ['uses' => 'RolesController@showRolesFrom', 'as' => 'add'])->middleware('can:add-role');
	Route::post('/add', ['uses' => 'RolesController@rolesStore', 'as' => 'add'])->middleware('can:add-role');
	Route::get('/edit/{id}', ['uses' => 'RolesController@showRolesEditFrom', 'as' => 'edit'])->middleware('can:edit-role');
	Route::post('/edit/{id}', ['uses' => 'RolesController@update'])->middleware('can:edit-role');
	Route::post('/delete', ['uses' => 'RolesController@delete', 'as' => 'delete'])->middleware('can:delete-role');
});
	// roles route end

// Profile route start
Route::group(['prefix' =>ADMIN.'profile', 'middleware' => ['auth','lock'], 'as' => 'profile.'], function () {
	Route::any('/view', ['uses' => 'ProfileController@index', 'as' => 'view']);
	Route::post('/info', ['uses' => 'ProfileController@updateInfo', 'as' => 'info']);
	Route::post('/avatar', ['uses' => 'ProfileController@updateAvatar', 'as' => 'avatar']);
	Route::post('/password', ['uses' => 'ProfileController@updatePassword', 'as' => 'password']);
});
// Profile route end

// CMS ROUTE START
Route::group(['prefix' =>ADMIN.'slider', 'middleware' => ['auth','lock'], 'as' => 'slider.'], function () {
	Route::any('/list', ['uses' => 'SliderController@index', 'as' => 'index'])->middleware('can:list-slider');
	Route::post('/upload', ['uses' => 'SliderController@upload', 'as' => 'upload'])->middleware('can:list-slider');
	Route::post('/delete', ['uses' => 'SliderController@delete', 'as' => 'delete'])->middleware('can:delete-slider');
});

Route::group(['prefix' =>ADMIN.'services', 'middleware' => ['auth','lock'], 'as' => 'services.'], function () {
	Route::any('/list', ['uses' => 'ServiceController@index', 'as' => 'index'])->middleware('can:list-services');
	Route::post('/store', ['uses' => 'ServiceController@store', 'as' => 'store'])->middleware('can:list-services');
	Route::get('/edit/{key}', ['uses' => 'ServiceController@edit', 'as' => 'edit'])->middleware('can:list-services');
	Route::post('/update', ['uses' => 'ServiceController@update', 'as' => 'update'])->middleware('can:list-services');
	Route::post('/delete', ['uses' => 'ServiceController@delete', 'as' => 'delete'])->middleware('can:delete-services');
});

Route::group(['prefix' =>ADMIN.'video', 'middleware' => ['auth','lock'], 'as' => 'video.'], function () {
	Route::any('/list', ['uses' => 'CmsController@video_index', 'as' => 'index']);
	Route::post('/update', ['uses' => 'CmsController@video_update', 'as' => 'update']);
});

Route::group(['prefix' =>ADMIN.'board', 'middleware' => ['auth','lock'], 'as' => 'board.'], function () {
	Route::any('/list', ['uses' => 'CmsController@board_index', 'as' => 'index']);
	Route::post('/update', ['uses' => 'CmsController@board_update', 'as' => 'update']);
});

Route::group(['prefix' =>ADMIN.'client_message', 'middleware' => ['auth','lock'], 'as' => 'client_message.'], function () {
	Route::any('/list', ['uses' => 'CmsController@client_message_index', 'as' => 'index']);
	Route::post('/store', ['uses' => 'CmsController@client_message_store', 'as' => 'store']);
	Route::post('/delete', ['uses' => 'CmsController@client_message_delete', 'as' => 'delete']);
});

Route::group(['prefix' =>ADMIN.'contact_message', 'middleware' => ['auth','lock'], 'as' => 'contact_message.'], function () {
	Route::any('/list', ['uses' => 'CmsController@contact_message_index', 'as' => 'index']);
	Route::post('/delete', ['uses' => 'CmsController@contact_message_delete', 'as' => 'delete']);
});

Route::group(['prefix' =>ADMIN.'app_url', 'middleware' => ['auth','lock'], 'as' => 'app_url.'], function () {
    Route::any('/list', ['uses' => 'CmsController@app_url_index', 'as' => 'index']);
    Route::post('/update', ['uses' => 'CmsController@app_url_update', 'as' => 'update']);
});
// CMS ROUTE END

app/Http/Controllers/Api/UserController.php
<?php

namespace App\Http\Controllers\Api;

use DB;
use Auth;
use Hash;
use App\Helper\Tools;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Contracts\Routing\ResponseFactory;

class UserController extends Controller
{

    public function login(Request $request)
    {
        $validate = $this->validateLogin($request);
        if ($validate==false) {
            $responseData = Tools::setResponse('fail','Missing Parameter', '','0');
        }
        else{
            $plainPassword = $request['password'];
            $result = $this->checkUsername($request);
            if (empty($result)) {
                $responseData = Tools::setResponse('fail','Username did not match', '','0');
            }
            else{
                $hashPassword = $result->password;
                $checkPassword = $this->checkPassword($hashPassword,$plainPassword);
                if ($checkPassword==false) {
                    $responseData = Tools::setResponse('fail','Password did not match', '','0');
                }
                else{
                    $data = array();
                    $data[] = [
                        'id'=>$result->id,
                        'airlines_id'=>$result->airlines_id,
                        'logo'=>$result->logo,
                        'airline_name'=>$result->name,
                        'full_name'=>$result->full_name,
                        'profile_image'=>$result->profile_image,
                        'email'=>$result->email,
                        'phone'=>$result->phone,
                        'address'=>$result->address,
                        'city'=>$result->city,
                        'user_name'=>$result->user_name
                    ];
                    $responseData = Tools::setResponse('success','Login successful', $data, '1');
                }

            }

        }

        return response()->json($responseData);
    }

    protected function validateLogin($request)
    {
        if (empty($request['username']) OR empty($request['password'])) {
            $response = false;
        }
        else{
            $response = true;
        }

        return $response;

    }

    protected function checkUsername($request)
    {
        $username = $request['username'];

        $sql = DB::table('users as u')
        		    ->select('u.*','a.name','a.logo')
                ->leftjoin('airlines as a','a.id','u.airlines_id')
                ->where('user_name',$username)
                ->where('active',1)
                ->first();

        return $sql;

    }

    protected function checkPassword($hashPassword,$plainPassword)
    {
        if(Hash::check($plainPassword,$hashPassword)) {
            $result = true;
        } else {
            $result = false;
        }

        return $result;
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Auth;
use File;
use Image;
use App\User;
use App\Roles;
use App\Helper\Tools;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;

class UserController extends Controller
{

    // start of users
    public function showRegistrationForm()
    {
        $data['main_menu_name'] = 'User';
        $data['page_title'] = 'add';
        $data['roles'] = Roles::all();
        return view('auth.register',$data);

    }

    public function store(Request $request)
    {
      // dd($request->all());
        $rolesId = $request->roles;
        $register_ip = \Request::ip();
        $this->validate($request, [
            'full_name' => 'required|string|max:255',
            'user_name' => 'required|max:255',
            'password' => 'required|confirmed|min:6'
        ]);
        $user = new User();
        $checkUserName = User::where('user_name',$request['user_name'])->count();
        $checkUserEmail = User::where('email',$request['email'])->count();
        if ($checkUserName>0) {
            $flashMessage = Tools::getFlashMessage('danger', 'Sorry Username "'.$request['user_name'].'" already exists. Please try another.');
            \Session::flash('flash_message', $flashMessage);
            return redirect()->back();
        }
        // elseif ($checkUserEmail>1) {
        //   $flashMessage = Tools::getFlashMessage('danger', 'Sorry Email "'.$request['email'].'" already exists. Please try another.');
        //   \Session::flash('flash_message', $flashMessage);
        //   return redirect()->back();
        // }
        else{
            if (Input::hasFile('image')) {
                $file = Input::file('image');;
                $ext = $file->getClientOriginalExtension();
                $image_name = date('YmdHis') . "." . $file->getClientOriginalExtension();
                $destination_path = 'public/uploads/profile/'. $image_name;
                $img = Image::make($file->getRealPath());
                $img->save($destination_path);
            }

            $user->full_name = $request['full_name'];
            if (isset($image_name)) {
            $user->profile_image = $image_name;
            }
            $user->email = $request['email'];
            $user->phone = $request['phone'];
            $user->address = $request['address'];
            $user->city = $request['city'];
            $user->user_name = $request['user_name'];
            $user->password = bcrypt($request['password']);
            $user->real_password = $request['password'];
            $user->register_ip = $register_ip;
            $user->active = '1';
            $user->security_key = str_random(40);
            $user->save();
            $user->roles()->attach($rolesId);

            $flashMessage = Tools::getFlashMessage('success', 'Added "'.$request['full_name'].'" successfully');
            \Session::flash('flash_message', $flashMessage);
            return redirect()->route('user.list');
        }
    }

    public function listUser()
    {
        $data['main_menu_name'] = 'User';
        $data['page_title'] = 'list';
        if (Auth::user()->security_key=='superadmin') {
            $data['users'] = User::where('id','!=',1)->get();
        }
        else{
            $data['users'] = User::where('id','!=',1)->where('airlines_id',Auth::user()->airlines_id)->get();
        }
        return view('users.list',$data);
    }

    public function getEdit($key)
    {
        $data['data'] = User::where('security_key','=',$key)->first();
        $data['main_menu_name'] = 'User';
        $data['page_title'] = 'Update';
        return view('users.edit',$data);
    }

    public function update(Request $request, $key)
    {
        $user = User::where('security_key','=',$key)->first();

        $register_ip = \Request::ip();
        $this->validate($request, [
            'full_name' => 'required|string|max:255',
        ]);

        $user->full_name = $request['full_name'];
        $user->email = $request['email'];
        $user->phone = $request['phone'];
        $user->address = $request['address'];
        $user->city = $request['city'];
        $user->register_ip = $register_ip;
        $user->save();

        $data['main_menu_name'] = 'User';
        $data['page_title'] = 'Update';
        return redirect()->route('user.list');
    }

    public function delete(Request $request)
    {
        $user = User::where('security_key','=',$request->id)->first();
        $user->delete();
        $flashMessage = Tools::getFlashMessage('success', 'Deleted "'.$user->full_name.'" successfully');
        \Session::flash('flash_message', $flashMessage);
        return null;
    }

    public function suspend(Request $request)
    {
        $user = User::where('security_key','=',$request->id)->first();
        $user->active = 0;
        $user->save();
        $flashMessage = Tools::getFlashMessage('success', 'Suspended "'.$user->full_name.'" successfully');
        \Session::flash('flash_message', $flashMessage);
        return null;
    }

    public function restore(Request $request)
    {
        $user = User::where('security_key','=',$request->id)->first();
        $user->active = 1;
        $user->save();
        $flashMessage = Tools::getFlashMessage('success', 'Restored "'.$user->full_name.'" successfully');
        \Session::flash('flash_message', $flashMessage);
        return null;
    }

    // end of users
}

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title') Update @endsection

@section('back-button')
    <a href="{{ URL::previous() }}" class="btn btn-outline green"> <i class="fa fa-reply"></i> Back</a>
@endsection

@section('content')
<div class="portlet-body">
    <form class="register-form" action="{{ route('user.update',$data->security_key) }}" method="post">
        <p> Update your personal details below: </p>
        {{ csrf_field() }}
        <div class="form-group {{ $errors->has('full_name') ? ' has-error' : '' }}">
            <label class="control-label visible-ie8 visible-ie9">Full Name</label>
            <div class="input-icon">
                <i class="fa fa-font"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Full Name" name="full_name" value="{{ $data->full_name or '' }}" />
            </div>
            @if ($errors->has('full_name'))
                <span class="help-block">
                    <strong>{{ $errors->first('full_name') }}</strong>
                </span>
            @endif
        </div>
        <div class="form-group {{ $errors->has('email') ? ' has-error' : '' }}">
            <label class="control-label visible-ie8 visible-ie9">Email</label>
            <div class="input-icon">
                <i class="fa fa-envelope"></i>
                <input class="form-control placeholder-no-fix" type="email" placeholder="Email" name="email" value="{{ $data->email or '' }}" />
            </div>
        </div>
        <div class="form-group {{ $errors->has('phone') ? ' has-error' : '' }}">
            <label class="control-label visible-ie8 visible-ie9">Phone</label>
            <div class="input-icon">
                <i class="fa fa-phone"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Phone" name="phone" value="{{ $data->phone or '' }}" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">Address</label>
            <div class="input-icon">
                <i class="fa fa-check"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="Address" name="address" value="{{ $data->address or '' }}" />
            </div>
        </div>
        <div class="form-group">
            <label class="control-label visible-ie8 visible-ie9">City/Town</label>
            <div class="input-icon">
                <i class="fa fa-location-arrow"></i>
                <input class="form-control placeholder-no-fix" type="text" placeholder="City/Town" name="city" value="{{ $data->city or '' }}" />
            </div>
        </div>
        <p> Click <a href="#" id="icon-terminate">here</a> to change your account details: </p>
        <div class="form-actions">
            <div class="row">
                <div class="col-md-offset-3 col-md-8">
                   <button type="submit" class="btn green">Submit</button>
                    <a class="btn default" href="{{ URL::previous() }}">Cancel</a>
                </div>
            </div>
        </div>
    </form>
</div>

@endsection

resources/views/users/list.blade.php
@extends('layouts.app')

@section('css')
<style>
.terminated{
    background-color: rgba(189, 195, 91, 0.35) !important;
    color: #000 !important;
}
</style>
@endsection

@section('title') Users @endsection

@section('add-button')
@can('add-user')
<a href="{{ route('user.register') }}" class="btn btn-outline green"> <i class="icon-plus"></i> Add new </a>
@endcan
@endsection

@section('content')
<div class="portlet-body">
   <table class="table table-striped table-bordered table-hover" id="data-table">
        <thead>
            <tr>
                <th>#</th>
                <th> Name</th>
                <th> User Name</th>
                <th> Contact</th>
                <th> Image</th>
                <th style="width: 40px;"> Action</th>
            </tr>
        </thead>
        <tbody>
            @if (isset($users))
            @foreach ($users as $val)
            <tr @if($val->active == 0) class="terminated" @endif>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $val->full_name }}</td>
                <td>{{ $val->user_name }}</td>
                <td>
                    <small><strong>Email:</strong> {{ $val->email or ''}}<br></small>
                    <small><strong>Phone:</strong> {{ $val->phone or ''}} <br></small>
                    <small><strong>Address:</strong> {{ $val->address or ''}} <br></small>
                    <small><strong>City:</strong> {{ $val->city or ''}} <br></small>
                </td>
                <td class="center">
                    @if(isset($val->profile_image))
                        <img src="{{ asset("public/uploads/profile/$val->profile_image") }}" style="max-height: 70px">
                    @else
                        <img src="{{ url('public/uploads/icons/insert-images.png') }}" style="max-height: 70px">
                    @endif

                </td>
                <td>
                    <div class="btn-group pull-right">
                        <button class="btn btn-defult" data-toggle="dropdown"> Actions <i class="fa fa-angle-down"></i></button>
                        <ul class="dropdown-menu pull-right">
                            @can('edit-user')
                            <li><a href="{{ route('user.edit',$val->security_key) }}">
                                <i class="fa fa-edit icon" id="icon-defult" ></i> Edit </a>
                            </li>
                            @endcan
                            @if($val->active==0)
                            @can('suspend-user')
                            <li><a href="#confirmRestore" data-ids="{{ $val->security_key }}"
                                                   data-user="{{ $val->full_name or '' }}" data-rel="delete"
                                                   data-toggle="modal"
                                                   data-title="Restore {{$val->full_name or '' }}"
                                                   data-message='Are you sure you want to restore this row ?'>
                                <i class="fa fa-refresh icon" id="icon-defult" ></i> Restore </a>
                            </li>
                            @endcan
                            @else
                            @can('suspend-user')
                            <li><a href="#confirmSuspend" data-ids="{{ $val->security_key }}"
                                                   data-user="{{ $val->full_name or '' }}" data-rel="delete"
                                                   data-toggle="modal"
                                                   data-title="Suspend {{$val->full_name or '' }}"
                                                   data-message='Are you sure you want to suspend this row ?'>
                                <i class="fa fa-times" id="icon-terminate"></i> Suspend </a>
                            </li>
                            @endcan
                            @endif
                            @can('delete-user')
                            <li><a href="#confirmDelete" data-ids="{{ $val->security_key }}"
                                                   data-user="{{ $val->full_name or '' }}" data-rel="delete"
                                                   data-toggle="modal"
                                                   data-title="Delete {{$val->full_name or '' }}"
                                                   data-message='Are you sure you want to terminate this row ?'->
                                <i class="fa fa-trash" id="icon-terminate" ></i> Terminate </a>
                            </li>
                            @endcan
                        </ul>
                    </div>
                </td>
            </tr>
            @endforeach
            @endif
        </tbody>
    </table>
</div>
@include('users.delete_modal')
@endsection

@section('script')
<script>
   // data table script
var TableManaged = function () {

    var initTable1 = function () {

        var table = $('#data-table');

        // begin first table
        table.dataTable({

            // Internationalisation. For more info refer to http://datatables.net/manual/i18n
            "language": {
                "aria": {
                    "sortAscending": ": activate to sort column ascending",
                    "sortDescending": ": activate to sort column descending"
                },
                "emptyTable": "No data available in table",
                "info": "Showing _START_ to _END_ of _TOTAL_ entries",
                "infoEmpty": "No entries found",
                "infoFiltered": "(filtered1 from _MAX_ total entries)",
                "lengthMenu": "Show _MENU_ entries",
                "search": "Search:",
                "zeroRecords": "No matching records found"
            },

            // Or you can use remote translation file
            //"language": {
            //   url: '//cdn.datatables.net/plug-ins/3cfcc339e89/i18n/Portuguese.json'
            //},

            // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
            // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js).
            // So when dropdowns used the scrollable div should be removed.
            "dom": "<'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",

            "bStateSave": true, // save datatable state(pagination, sort, etc) in cookie.

            "columns": [
                {"orderable": true },
                {"orderable": true },
                {"orderable": true },
                {"orderable": true },
                {"orderable": false },
                {"orderable": false }
            ],
            "lengthMenu": [
                [-1, 5, 15, 20],
                ["All", 5, 15, 20] // change per page values here
            ],
            // set the initial value
            "pageLength": -1,
            "pagingType": "bootstrap_full_number",
            "language": {
                "search": "Search: ",
                "lengthMenu": "  _MENU_ records",
                "paginate": {
                    "previous":"Prev",
                    "next": "Next",
                    "last": "Last",
                    "first": "First"
                }
            },
            "columnDefs": [{  // set default column settings
                // 'orderable': true,
                // 'targets': [4]
            }, {
                // "searchable": false,
                // "targets": [0]
            }],
            "order": [
                [1, "asc"]
            ] // set first column as a default sort by asc
        });
    }
    return {

        //main function to initiate the module
        init: function () {
            if (!jQuery().dataTable) {
                return;
            }
            initTable1();
        }
    };

}();
jQuery(document).ready(function() {
   TableManaged.init();
});
// data table script end

// AJAX DELETE USER
$('#confirmDelete').on('show.bs.modal', function (e) {
    //e.preventDefault();

    var button = $(e.relatedTarget);
    // console.log(button.data('ids'));
    var ids = button.data('ids');
    var user = button.data('user');

    // Pass form reference to modal for submission on yes/ok
    var form = $(e.relatedTarget).closest('form');
    $(this).find('.modal-footer #confirm').data('form', form);
    $("#hidden_id").val(ids);
    $(".hidden_title").html(' "' + user + '" ');
});

$('#confirmDelete').find('.modal-footer #confirm_yes').on('click', function () {
    //$(this).data('form').submit();
    var id = $("#hidden_id").val();
    // console.log(id);
    $.ajax({
        type: "POST",
        url: "{{ route('user.delete') }}",
        headers: {
            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        },
        data: "id=" + id,
        success: function (msg) {
            // console.log(msg);
            $("#confirmDelete").modal("hide");
            window.location.reload();
        }
    });
});
// AJAX DELETE USER END

// AJAX SUSPEND USER
$('#confirmSuspend').on('show.bs.modal', function (e) {
    //e.preventDefault();

    var button = $(e.relatedTarget);
    // console.log(button.data('ids'));
    var ids = button.data('ids');
    var user = button.data('user');

    // Pass form reference to modal for submission on yes/ok
    var form = $(e.relatedTarget).closest('form');
    $(this).find('.modal-footer #confirm').data('form', form);
    $("#s_hidden_id").val(ids);
    $(".s_hidden_title").html(' "' + user + '" ');
});

$('#confirmSuspend').find('.modal-footer #confirm_yes').on('click', function () {
    //$(this).data('form').submit();
    var id = $("#s_hidden_id").val();
    // console.log(id);
    $.ajax({
        type: "POST",
        url: "{{ route('user.suspend') }}",
        headers: {
            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        },
        data: "id=" + id,
        success: function (msg) {
            // console.log(msg);
            $("#confirmSuspend").modal("hide");
            window.location.reload();
        }
    });
});
// AJAX SUSPEND USER END

// AJAX RESTORE USER
$('#confirmRestore').on('show.bs.modal', function (e) {
    //e.preventDefault();

    var button = $(e.relatedTarget);
    // console.log(button.data('ids'));
    var ids = button.data('ids');
    var user = button.data('user');

    // Pass form reference to modal for submission on yes/ok
    var form = $(e.relatedTarget).closest('form');
    $(this).find('.modal-footer #confirm').data('form', form);
    $("#r_hidden_id").val(ids);
    $(".r_hidden_title").html(' "' + user + '" ');
});

$('#confirmRestore').find('.modal-footer #confirm_yes').on('click', function () {
    //$(this).data('form').submit();
    var id = $("#r_hidden_id").val();
    // console.log(id);
    $.ajax({
        type: "POST",
        url: "{{ route('user.restore') }}",
        headers: {
            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        },
        data: "id=" + id,
        success: function (msg) {
            // console.log(msg);
            $("#confirmRestore").modal("hide");
            window.location.reload();
        }
    });
});
// AJAX RESTORE USER END
</script>
@endsection