routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
define("ADMIN", "admin/");
define("ADMIN_NAME", "admin.");
// define('USER_IMAGE','public/uploads/profile/avatar.png');
// define("ADMIN", "admin/");
define('INSERT_IMAGES','public/uploads/icons/insert-images.png');
// Admin Routes Start
// FRONTEND ROUTE


Route::get('/',['uses'=>'FrontController@index', 'as'=>'index']);
Route::get('/services',['uses'=>'FrontController@services', 'as'=>'services']);
Route::post('/contact_message',['uses'=>'FrontController@contact_message', 'as'=>'contact_message']);
// FORNTEND ROUTE END

// Auth::routes();

// LOGIN ROUTE START
Route::get(ADMIN.'login', ['uses'=>'Auth\LoginController@showLoginForm','as'=>'login']);
Route::post(ADMIN.'login', ['uses'=>'Auth\LoginController@login']);
Route::get(ADMIN.'logout',['uses'=>'Auth\LoginController@logout', 'as'=> 'logout']);
// LOGIN ROUTE END

// Route::post('logout', 'Auth\LoginController@logout')->name('logout');
// Route::get(ADMIN.'home', 'HomeController@index')->name('home');
Route::get(ADMIN.'/', ['uses'=>'HomeController@index', 'as'=>'home']);
Route::get(ADMIN.'/lock', ['uses' => 'ProfileController@lock', 'as' => 'lock']);
Route::post(ADMIN.'/lock', ['uses' => 'ProfileController@unLock', 'as' => 'lock']);
// Module routes start
Route::group(['prefix' =>ADMIN.'module', 'middleware' => ['auth','lock'], 'as' => 'module.'], function () {
	Route::get('/add',['uses' => 'ModuleController@create', 'as' => 'create'])->middleware('can:add-module');
	Route::post('/add',['uses' => 'ModuleController@store'])->middleware('can:add-module');
	Route::get('/list',['uses' => 'ModuleController@listModule','as' => 'list' ])->middleware('can:list-module');
	Route::get('/edit/{key}',['uses' => 'ModuleController@editModuleForm','as' => 'edit' ])->middleware('can:edit-module');
	Route::post('/edit/{key}',['uses' => 'ModuleController@updateModule'])->middleware('can:edit-module');
	Route::post('/delete',['uses' => 'ModuleController@deleteModule','as' => 'delete' ])->middleware('can:delete-module');
});
// Module route end

// Menu route start
Route::group(['prefix' =>ADMIN.'menu', 'middleware' => ['auth','lock'], 'as' => 'menu.'], function () {
	Route::get('/view/{id}',['uses' => 'ModuleController@viewMenu', 'as' => 'view']);
	Route::get('/add/{id}/{name}',['uses' => 'ModuleController@createMenu', 'as' => 'create']);
	Route::post('/store',['uses' => 'ModuleController@storeMenu','as' => 'store']);
});
// Menu route end

// users route start
Route::group(['prefix' =>ADMIN.'user', 'middleware' => ['auth','lock'], 'as' => 'user.'], function () {
	Route::get('/register',['uses'=>'UserController@showRegistrationForm', 'as'=> 'register'])->middleware('can:add-user');
	Route::post('/register',['uses'=>'UserController@store'])->middleware('can:add-user');
	Route::get('/list',['uses'=>'UserController@listUser', 'as' => 'list'])->middleware('can:list-user');
	Route::get('/edit/{key}',['uses'=>'UserController@getEdit', 'as' => 'edit'])->middleware('can:edit-user');
	Route::post('/update/{key}',['uses'=>'UserController@update', 'as'=>'update'])->middleware('can:edit-user');
	Route::post('/delete',['uses'=>'UserController@delete', 'as'=>'delete'])->middleware('can:delete-user');
	Route::post('/suspend',['uses'=>'UserController@suspend', 'as'=>'suspend'])->middleware('can:suspend-user');
	Route::post('/restore',['uses'=>'UserController@restore', 'as'=>'restore'])->middleware('can:suspend-user');
});
// users route end

// roles route start
Route::group(['prefix' =>ADMIN.'role', 'middleware' => ['auth','lock'], 'as' => 'role.'], function () {
	Route::any('/list', ['uses' => 'RolesController@index', 'as' => 'list'])->middleware('can:list-role');
	Route::any('/add', ['uses' => 'RolesController@showRolesFrom', 'as' => 'add'])->middleware('can:add-role');
	Route::post('/add', ['uses' => 'RolesController@rolesStore', 'as' => 'add'])->middleware('can:add-role');
	Route::get('/edit/{id}', ['uses' => 'RolesController@showRolesEditFrom', 'as' => 'edit'])->middleware('can:edit-role');
	Route::post('/edit/{id}', ['uses' => 'RolesController@update'])->middleware('can:edit-role');
	Route::post('/delete', ['uses' => 'RolesController@delete', 'as' => 'delete'])->middleware('can:delete-role');
});
	// roles route end

// Profile route start
Route::group(['prefix' =>ADMIN.'profile', 'middleware' => ['auth','lock'], 'as' => 'profile.'], function () {
	Route::any('/view', ['uses' => 'ProfileController@index', 'as' => 'view']);
	Route::post('/info', ['uses' => 'ProfileController@updateInfo', 'as' => 'info']);
	Route::post('/avatar', ['uses' => 'ProfileController@updateAvatar', 'as' => 'avatar']);
	Route::post('/password', ['uses' => 'ProfileController@updatePassword', 'as' => 'password']);
});
// Profile route end

// CMS ROUTE START
Route::group(['prefix' =>ADMIN.'slider', 'middleware' => ['auth','lock'], 'as' => 'slider.'], function () {
	Route::any('/list', ['uses' => 'SliderController@index', 'as' => 'index'])->middleware('can:list-slider');
	Route::post('/upload', ['uses' => 'SliderController@upload', 'as' => 'upload'])->middleware('can:list-slider');
	Route::post('/delete', ['uses' => 'SliderController@delete', 'as' => 'delete'])->middleware('can:delete-slider');
});

Route::group(['prefix' =>ADMIN.'services', 'middleware' => ['auth','lock'], 'as' => 'services.'], function () {
	Route::any('/list', ['uses' => 'ServiceController@index', 'as' => 'index'])->middleware('can:list-services');
	Route::post('/store', ['uses' => 'ServiceController@store', 'as' => 'store'])->middleware('can:list-services');
	Route::get('/edit/{key}', ['uses' => 'ServiceController@edit', 'as' => 'edit'])->middleware('can:list-services');
	Route::post('/update', ['uses' => 'ServiceController@update', 'as' => 'update'])->middleware('can:list-services');
	Route::post('/delete', ['uses' => 'ServiceController@delete', 'as' => 'delete'])->middleware('can:delete-services');
});

Route::group(['prefix' =>ADMIN.'video', 'middleware' => ['auth','lock'], 'as' => 'video.'], function () {
	Route::any('/list', ['uses' => 'CmsController@video_index', 'as' => 'index']);
	Route::post('/update', ['uses' => 'CmsController@video_update', 'as' => 'update']);
});

Route::group(['prefix' =>ADMIN.'board', 'middleware' => ['auth','lock'], 'as' => 'board.'], function () {
	Route::any('/list', ['uses' => 'CmsController@board_index', 'as' => 'index']);
	Route::post('/update', ['uses' => 'CmsController@board_update', 'as' => 'update']);
});

Route::group(['prefix' =>ADMIN.'client_message', 'middleware' => ['auth','lock'], 'as' => 'client_message.'], function () {
	Route::any('/list', ['uses' => 'CmsController@client_message_index', 'as' => 'index']);
	Route::post('/store', ['uses' => 'CmsController@client_message_store', 'as' => 'store']);
	Route::post('/delete', ['uses' => 'CmsController@client_message_delete', 'as' => 'delete']);
});

Route::group(['prefix' =>ADMIN.'contact_message', 'middleware' => ['auth','lock'], 'as' => 'contact_message.'], function () {
	Route::any('/list', ['uses' => 'CmsController@contact_message_index', 'as' => 'index']);
	Route::post('/delete', ['uses' => 'CmsController@contact_message_delete', 'as' => 'delete']);
});

Route::group(['prefix' =>ADMIN.'app_url', 'middleware' => ['auth','lock'], 'as' => 'app_url.'], function () {
    Route::any('/list', ['uses' => 'CmsController@app_url_index', 'as' => 'index']);
    Route::post('/update', ['uses' => 'CmsController@app_url_update', 'as' => 'update']);
});
// CMS ROUTE END

app/ContactMessage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ContactMessage extends Model
{
    protected $table = 'contact_messages';
}

resources/views/contact_message/index.blade.php
@extends('layouts.app')

@section('css')
{{-- <link href="{{ asset('public\assets\lightbox\src\css\lightbox.css')}}" rel="stylesheet" type="text/css" --}}
      xmlns="http://www.w3.org/1999/html"/>
<link href="{{ url('public/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css')}}" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" href="{{ asset('public/frontend/css/style.css')}}"/>


@endsection

@section('title') Contact Listing @endsection

@section('add-button')
@can('add-slider')
@endcan
@endsection

@section('content')
<div class="portlet-body">
  <div class="row">
    <div class="col-md-12">
          <table class="table table-striped table-bordered table-hover">
              <thead>
              <tr>
                  <th>#</th>
                  <th> Name</th>
                  <th> Email</th>
                  <th> Subject</th>
                  <th> Message</th>
                  <th> Client Ip</th>
                  <th> Created At</th>
                  <th style="width: 40px;"> Action</th>
              </tr>
              </thead>
              <tbody>

              @if (isset($message))
                  @foreach ($message as $val)
                      <tr>
                          <td>{{ $loop->iteration }}</td>
                          <td> {{ $val->name }} </td>
                          <td>{{ $val->email }}</td>
                          <td>{{ $val->subject }}</td>
                          <td style="text-align: center;">
                              <a href="#view" data-toggle="modal" data-ids="{{ $val->name }}" data-user="{{ $val->message }}">View</a>
                          </td>
                          <td> {{ $val->client_ip }} </td>
                          <td>{{ $val->created_at->diffForHumans() }}</td>
                          <td style="text-align: center; width: 100px;">
                              <a href="{{ route('services.edit',$val->unique_key) }}" style="padding-right: 10px; ">
                                  <i class="fa fa-pencil icon" id="icon-defult" ></i></a>
                              <a href="#confirmDelete" data-ids="{{ $val->id }}"
                                 data-user="" data-rel="delete"
                                 data-toggle="modal"
                                 data-title="Delete"
                                 data-message='Are you sure you want to terminate this row ?' style="padding-left: 10px; ">
                                  <i class="fa fa-trash" id="icon-terminate" ></i></a>
                          </td>
                      </tr>
              @endforeach
              @endif
          </table>
    </div> 
  </div>
</div>

@include('contact_message.model')
@endsection

@section('script')

{{-- <script src="{{ asset('public\assets\lightbox\src\js\lightbox.js')}}" type="text/javascript"></script> --}}
<script src="{{url('public/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.js')}}" type="text/javascript"></script>

<script>
   // data table script
var TableManaged = function () {

    var initTable1 = function () {

        var table = $('#data-table');

        // begin first table
        table.dataTable({

            // Internationalisation. For more info refer to http://datatables.net/manual/i18n
            "language": {
                "aria": {
                    "sortAscending": ": activate to sort column ascending",
                    "sortDescending": ": activate to sort column descending"
                },
                "emptyTable": "No data available in table",
                "info": "Showing _START_ to _END_ of _TOTAL_ entries",
                "infoEmpty": "No entries found",
                "infoFiltered": "(filtered1 from _MAX_ total entries)",
                "lengthMenu": "Show _MENU_ entries",
                "search": "Search:",
                "zeroRecords": "No matching records found"
            },

            // Or you can use remote translation file
            //"language": {
            //   url: '//cdn.datatables.net/plug-ins/3cfcc339e89/i18n/Portuguese.json'
            //},

            // Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
            // setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js).
            // So when dropdowns used the scrollable div should be removed.
            "dom": "<'row'<'col-md-6 col-sm-12'l><'col-md-6 col-sm-12'f>r>t<'row'<'col-md-5 col-sm-12'i><'col-md-7 col-sm-12'p>>",

            "bStateSave": true, // save datatable state(pagination, sort, etc) in cookie.

            "columns": [
                {"orderable": true },
                {"orderable": false },
                {"orderable": true },
                {"orderable": true },
                {"orderable": true },
                {"orderable": true },
                {"orderable": true },
                {"orderable": false }
            ],
            "lengthMenu": [
                [-1, 5, 15, 20],
                ["All", 5, 15, 20] // change per page values here
            ],
            // set the initial value
            "pageLength": -1,
            "pagingType": "bootstrap_full_number",
            "language": {
                "search": "Search: ",
                "lengthMenu": "  _MENU_ records",
                "paginate": {
                    "previous":"Prev",
                    "next": "Next",
                    "last": "Last",
                    "first": "First"
                }
            },
            "columnDefs": [{  // set default column settings
                'orderable': true,
                'targets': [4]
            }, {
                "searchable": false,
                "targets": [0]
            }],
            "order": [
                [0, "asc"]
            ] // set first column as a default sort by asc
        });
    }
    return {

        //main function to initiate the module
        init: function () {
            if (!jQuery().dataTable) {
                return;
            }
            initTable1();
        }
    };

}();
jQuery(document).ready(function() {
   TableManaged.init();
});


 $('#view').on('show.bs.modal', function (e) {
       //e.preventDefault();

       var button = $(e.relatedTarget);
         
       var ids = button.data('ids');
       var user = button.data('user');

       // Pass form reference to modal for submission on yes/ok
       var form = $(e.relatedTarget).closest('form');
       $(this).find('.modal-footer #confirm').data('form', form);
       $("#title").html(ids);
       $("#body").html(user);
   });
 
// AJAX DELETE
$('#confirmDelete').on('show.bs.modal', function (e) {
    //e.preventDefault();

    var button = $(e.relatedTarget);
     // console.log(button.data('ids'));
    var ids = button.data('ids');
    var user = button.data('user');

    // Pass form reference to modal for submission on yes/ok
    var form = $(e.relatedTarget).closest('form');
    $(this).find('.modal-footer #confirm').data('form', form);
    $("#hidden_id").val(ids);
    // alert(ids);
    $(".hidden_title").html(' "' + user + '" ');
});

$('#confirmDelete').find('.modal-footer #confirm_yes').on('click', function () {
    //$(this).data('form').submit();
    var id = $("#hidden_id").val();
    // console.log(id);
    $.ajax({
        type: "POST",
        url: "{{ route('contact_message.delete') }}",
        headers: {
            'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
        },
        data: "id=" + id,
        success: function (msg) {
            // console.log(msg);
            $("#confirmDelete").modal("hide");
            window.location.reload();
        }
    });
});

</script>

@endsection

resources/views/contact_message/model.blade.php
<div class="modal fade bs-modal-sm" id="view" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title"><i class="fa fa-info-circle" id="icon-terminate" ></i> <span id="title"></span>
                </h4>
            </div>
            <div class="modal-body"> <span id="body"></span></div>
           {{--  <input type="hidden" class="hidden_id"> --}}
            <div class="modal-footer">
               
                <button type="button" class="btn btn-defult" data-dismiss="modal"><i class="icon-close" id="icon-terminate"></i>
                    Close
                </button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
</div>

<div class="modal fade bs-modal-sm" id="confirmDelete" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title"><i class="fa fa-info-circle" id="icon-terminate" ></i> Terminate Permanently
                </h4>
            </div>

            <div class="modal-body"> Do you want to Delete this Item ?</div>

            <input type="hidden" id="hidden_id">
            <div class="modal-footer">
                <button type="button" class="btn btn-defult green confirm_yes" id="confirm_yes"><i class="icon-check"></i> Yes
                </button>
                <button type="button" class="btn btn-defult" data-dismiss="modal"><i class="icon-close" id="icon-terminate"></i>
                    No
                </button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
</div>